api_version = "2025-07"

[[extensions]]
name = "t:name"
handle = "uncle-clarence-cart-transform"
type = "function"
uid = "aca8aef5-7744-7e02-d9ad-fb1d94493dece3c4f9a7"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
